name: 99 problems continuous integration
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        id: problems-cache
        with:
          path: deps, _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - run: echo ${{ steps.cache-npm.outputs.cache-hit }}
      - uses: actions/checkout@v3.3.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14.0
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v4
        id: problems-cache
        with:
          path: deps, _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - run: echo ${{ steps.cache-npm.outputs.cache-hit }}
      - uses: actions/checkout@v3.3.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14.0
      - run: mix test
